---
- name: Install JRE
  apt:
    name: openjdk-11-jre
    state: present
  tags: jre

- name: Create chronograph user
  user:
    system: yes
    name: chronograph
  register: chronograph_user

- set_fact:
    deploy_user: "{{ chronograph_user.name }}"
    deploy_group: "{{ chronograph_user.group }}"
    deploy_chronograph_jar: "{{ chronograph_user.home }}/chronograph.jar"
    deploy_chronograph_config: "{{ chronograph_user.home }}/config.edn"

- name: Copy the jar
  copy:
    src: "{{ chronograph_jar }}"
    dest: "{{ deploy_chronograph_jar }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: '0600'

- name: Copy the configuration
  copy:
    src: "{{ chronograph_config }}"
    dest: "{{ deploy_chronograph_config }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: '0600'

- name: Copy the service file
  template:
    src: chronograph.service.j2
    dest: /etc/systemd/system/chronograph.service
    owner: root
    group: root
    mode: '0600'

- name: Enable and start the service
  systemd:
    name: chronograph
    daemon_reload: yes
    state: restarted
    enabled: true
